"""
prompts 模块
包含所有 Agent 的 Prompt 模板
"""

from .research import SYSTEM_PROMPT as RESEARCH_SYSTEM_PROMPT
from .research import USER_PROMPT as RESEARCH_USER_PROMPT
from .research import FEW_SHOT_EXAMPLES as RESEARCH_EXAMPLES

from .creator import SYSTEM_PROMPT as CREATOR_SYSTEM_PROMPT
from .creator import USER_PROMPT as CREATOR_USER_PROMPT
from .creator import FEW_SHOT_EXAMPLES as CREATOR_EXAMPLES

from .reviewer import SYSTEM_PROMPT as REVIEWER_SYSTEM_PROMPT
from .reviewer import USER_PROMPT as REVIEWER_USER_PROMPT
from .reviewer import FEW_SHOT_EXAMPLES as REVIEWER_EXAMPLES

from .optimizer import SYSTEM_PROMPT as OPTIMIZER_SYSTEM_PROMPT
from .optimizer import USER_PROMPT as OPTIMIZER_USER_PROMPT
from .optimizer import FEW_SHOT_EXAMPLES as OPTIMIZER_EXAMPLES

from .image import SYSTEM_PROMPT as IMAGE_SYSTEM_PROMPT
from .image import USER_PROMPT as IMAGE_USER_PROMPT
from .image import FEW_SHOT_EXAMPLES as IMAGE_EXAMPLES

__all__ = [
    "RESEARCH_SYSTEM_PROMPT",
    "RESEARCH_USER_PROMPT",
    "RESEARCH_EXAMPLES",
    "CREATOR_SYSTEM_PROMPT",
    "CREATOR_USER_PROMPT",
    "CREATOR_EXAMPLES",
    "REVIEWER_SYSTEM_PROMPT",
    "REVIEWER_USER_PROMPT",
    "REVIEWER_EXAMPLES",
    "OPTIMIZER_SYSTEM_PROMPT",
    "OPTIMIZER_USER_PROMPT",
    "OPTIMIZER_EXAMPLES",
    "IMAGE_SYSTEM_PROMPT",
    "IMAGE_USER_PROMPT",
    "IMAGE_EXAMPLES",
]
